name: start_pro
description: "A new Flutter project."


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fpdart: ^1.1.1
  google_fonts: ^6.2.1
  flutter_locales: ^3.0.4
  flutter_screenutil: ^5.9.3
  rounded_loading_button_plus: ^3.0.1
  gap: ^3.0.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.2
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  firebase_database: ^11.3.4
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  cloud_firestore: ^5.6.5
  delightful_toast: ^1.1.0
  flutter_native_splash: ^2.4.5
  flutter_launcher_icons: ^0.14.3
  rename_app: ^1.6.2
  fluid_bottom_nav_bar: ^1.4.0
  adaptive_theme: ^3.7.0
  phone_form_field: ^3.0.1
  graphql_flutter: ^5.2.0-beta.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  logger: ^2.5.0
  cached_network_image: ^3.4.1
  skeletonizer: ^1.4.3
  flutter_markdown: ^0.7.6+2
  flutter_debouncer: ^2.0.0
  lottie: ^3.3.1
  flutter_colorpicker: ^1.1.0
  dio: ^5.8.0+1
  flutter_staggered_grid_view: ^0.7.0
  fluttertoast: ^8.2.4
  http: ^1.3.0
  url_launcher:  ^6.1.7

 




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/locales/
    - .env
    - assets/animations/


flutter_native_splash:
  image: assets/images/logo.png
  color: #0c3745
  android: true
  ios: true
  web: false
